// Data layer for loading region and location JSON files statically.
import type {
  Barangay,
  Location,
  RawBarangayFile,
  RawRegionData,
  Region,
  SearchResult,
} from "../types/location.js";

// ---------------------------------------------------------------------------
// Static JSON imports
// All 19 region data files are imported at build time.
// ---------------------------------------------------------------------------

import regionsJson from "../../data/regions.json";

import bangsamoroData from "../../data/lgu/bangsamoro-autonomous-region-in-muslim-mindanao.json";
import carData from "../../data/lgu/cordillera-administrative-region.json";
import ncrData from "../../data/lgu/national-capital-region.json";
import nirData from "../../data/lgu/negros-island-region.json";
import region1Data from "../../data/lgu/region-i-ilocos-region.json";
import region2Data from "../../data/lgu/region-ii-cagayan-valley.json";
import region3Data from "../../data/lgu/region-iii-central-luzon.json";
import region4aData from "../../data/lgu/region-iva-calabarzon.json";
import region4bData from "../../data/lgu/region-ivb-mimaropa.json";
import region5Data from "../../data/lgu/region-v-bicol-region.json";
import region6Data from "../../data/lgu/region-vi-western-visayas.json";
import region7Data from "../../data/lgu/region-vii-central-visayas.json";
import region8Data from "../../data/lgu/region-viii-eastern-visayas.json";
import region9Data from "../../data/lgu/region-ix-zamboanga-peninsula.json";
import region10Data from "../../data/lgu/region-x-northern-mindanao.json";
import region11Data from "../../data/lgu/region-xi-davao-region.json";
import region12Data from "../../data/lgu/region-xii-soccsksargen.json";
import region13Data from "../../data/lgu/region-xiiicaraga.json";
import sgaData from "../../data/lgu/special-geographic-area.json";

// ---------------------------------------------------------------------------
// Barangay data — per-region files (data/lgu/barangay/<slug>.json)
// Generated by: pnpm split-barangays
// ---------------------------------------------------------------------------

import bangsamoroBarangays from "../../data/lgu/barangay/bangsamoro-autonomous-region-in-muslim-mindanao.json";
import carBarangays from "../../data/lgu/barangay/cordillera-administrative-region.json";
import ncrBarangays from "../../data/lgu/barangay/national-capital-region.json";
import nirBarangays from "../../data/lgu/barangay/negros-island-region.json";
import region1Barangays from "../../data/lgu/barangay/region-i-ilocos-region.json";
import region2Barangays from "../../data/lgu/barangay/region-ii-cagayan-valley.json";
import region3Barangays from "../../data/lgu/barangay/region-iii-central-luzon.json";
import region4aBarangays from "../../data/lgu/barangay/region-iva-calabarzon.json";
import region4bBarangays from "../../data/lgu/barangay/region-ivb-mimaropa.json";
import region5Barangays from "../../data/lgu/barangay/region-v-bicol-region.json";
import region6Barangays from "../../data/lgu/barangay/region-vi-western-visayas.json";
import region7Barangays from "../../data/lgu/barangay/region-vii-central-visayas.json";
import region8Barangays from "../../data/lgu/barangay/region-viii-eastern-visayas.json";
import region9Barangays from "../../data/lgu/barangay/region-ix-zamboanga-peninsula.json";
import region10Barangays from "../../data/lgu/barangay/region-x-northern-mindanao.json";
import region11Barangays from "../../data/lgu/barangay/region-xi-davao-region.json";
import region12Barangays from "../../data/lgu/barangay/region-xii-soccsksargen.json";
import region13Barangays from "../../data/lgu/barangay/region-xiiicaraga.json";

const BARANGAY_DATA_MAP: Record<string, RawBarangayFile> = {
  "bangsamoro-autonomous-region-in-muslim-mindanao":
    bangsamoroBarangays as RawBarangayFile,
  "cordillera-administrative-region": carBarangays as RawBarangayFile,
  "national-capital-region": ncrBarangays as RawBarangayFile,
  "negros-island-region": nirBarangays as RawBarangayFile,
  "region-i-ilocos-region": region1Barangays as RawBarangayFile,
  "region-ii-cagayan-valley": region2Barangays as RawBarangayFile,
  "region-iii-central-luzon": region3Barangays as RawBarangayFile,
  "region-iva-calabarzon": region4aBarangays as RawBarangayFile,
  "region-ivb-mimaropa": region4bBarangays as RawBarangayFile,
  "region-v-bicol-region": region5Barangays as RawBarangayFile,
  "region-vi-western-visayas": region6Barangays as RawBarangayFile,
  "region-vii-central-visayas": region7Barangays as RawBarangayFile,
  "region-viii-eastern-visayas": region8Barangays as RawBarangayFile,
  "region-ix-zamboanga-peninsula": region9Barangays as RawBarangayFile,
  "region-x-northern-mindanao": region10Barangays as RawBarangayFile,
  "region-xi-davao-region": region11Barangays as RawBarangayFile,
  "region-xii-soccsksargen": region12Barangays as RawBarangayFile,
  "region-xiiicaraga": region13Barangays as RawBarangayFile,
  // special-geographic-area has no barangay data
};

// ---------------------------------------------------------------------------
// Build a slug → RawRegionData lookup map
// ---------------------------------------------------------------------------

const REGION_DATA_MAP: Record<string, RawRegionData> = {
  "bangsamoro-autonomous-region-in-muslim-mindanao":
    bangsamoroData as RawRegionData,
  "cordillera-administrative-region": carData as RawRegionData,
  "national-capital-region": ncrData as RawRegionData,
  "negros-island-region": nirData as RawRegionData,
  "region-i-ilocos-region": region1Data as RawRegionData,
  "region-ii-cagayan-valley": region2Data as RawRegionData,
  "region-iii-central-luzon": region3Data as RawRegionData,
  "region-iva-calabarzon": region4aData as RawRegionData,
  "region-ivb-mimaropa": region4bData as RawRegionData,
  "region-v-bicol-region": region5Data as RawRegionData,
  "region-vi-western-visayas": region6Data as RawRegionData,
  "region-vii-central-visayas": region7Data as RawRegionData,
  "region-viii-eastern-visayas": region8Data as RawRegionData,
  "region-ix-zamboanga-peninsula": region9Data as RawRegionData,
  "region-x-northern-mindanao": region10Data as RawRegionData,
  "region-xi-davao-region": region11Data as RawRegionData,
  "region-xii-soccsksargen": region12Data as RawRegionData,
  "region-xiiicaraga": region13Data as RawRegionData,
  "special-geographic-area": sgaData as RawRegionData,
};

// ---------------------------------------------------------------------------
// Slug generation
// ---------------------------------------------------------------------------

/** Derive a URL-safe slug from a location name. */
export function toSlug(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// ---------------------------------------------------------------------------
// Public data accessors
// ---------------------------------------------------------------------------

/** Return the list of all regions. */
export function getRegions(): Region[] {
  return regionsJson as Region[];
}

/** Return the region metadata for a given slug. */
export function getRegion(slug: string): Region | null {
  const regions = getRegions();
  return regions.find((r) => r.slug === slug) ?? null;
}

/** Return the raw region data object for a given slug. */
export function getRegionData(slug: string): RawRegionData | null {
  return REGION_DATA_MAP[slug] ?? null;
}

// ---------------------------------------------------------------------------
// Data normalisation
// ---------------------------------------------------------------------------

/**
 * Flatten a raw region data object into a consistent array of Location objects.
 * Appends province slugs for disambiguation when needed.
 */
export function flattenLocations(data: RawRegionData): Location[] {
  // --- First pass: build raw entries ---
  interface RawEntry {
    name: string;
    baseSlug: string;
    type: "city" | "municipality";
    zip_code: string | null;
    province: string | null;
  }

  const raw: RawEntry[] = [];

  if (data.provinces) {
    for (const province of data.provinces) {
      const provinceName = province.province;

      for (const city of province.cities ?? []) {
        raw.push({
          name: city.city,
          baseSlug: toSlug(city.city),
          type: "city",
          zip_code: city.zip_code ?? null,
          province: provinceName,
        });
      }

      for (const municipality of province.municipalities ?? []) {
        raw.push({
          name: municipality.municipality,
          baseSlug: toSlug(municipality.municipality),
          type: "municipality",
          zip_code: municipality.zip_code ?? null,
          province: provinceName,
        });
      }
    }
  } else {
    for (const city of data.cities ?? []) {
      raw.push({
        name: city.city,
        baseSlug: toSlug(city.city),
        type: "city",
        zip_code: city.zip_code ?? null,
        province: null,
      });
    }

    for (const municipality of data.municipalities ?? []) {
      raw.push({
        name: municipality.municipality,
        baseSlug: toSlug(municipality.municipality),
        type: "municipality",
        zip_code: municipality.zip_code ?? null,
        province: null,
      });
    }
  }

  // --- Second pass: count duplicate base slugs ---
  const slugCount = new Map<string, number>();
  for (const entry of raw) {
    slugCount.set(entry.baseSlug, (slugCount.get(entry.baseSlug) ?? 0) + 1);
  }

  // --- Third pass: assign final slugs, disambiguating duplicates ---
  const locations: Location[] = [];
  for (const entry of raw) {
    const count = slugCount.get(entry.baseSlug) ?? 1;
    let finalSlug: string;

    if (count > 1 && entry.province !== null) {
      // Append province slug to disambiguate — double-hyphen separator
      finalSlug = `${entry.baseSlug}--${toSlug(entry.province)}`;
    } else {
      finalSlug = entry.baseSlug;
    }

    locations.push({
      name: entry.name,
      slug: finalSlug,
      type: entry.type,
      zip_code: entry.zip_code,
      province: entry.province,
    });
  }

  return locations;
}

// ---------------------------------------------------------------------------
// Search index
// ---------------------------------------------------------------------------

/**
 * A flat search index built once at module load time.
 *
 * Each entry stores the lowercased name alongside the full SearchResult so
 * that searches can be performed with a simple `includes()` check without
 * re-lowercasing on every request.
 */
interface SearchIndexEntry {
  nameLower: string;
  result: SearchResult;
}

let _searchIndex: SearchIndexEntry[] | null = null;

function buildSearchIndex(): SearchIndexEntry[] {
  const index: SearchIndexEntry[] = [];
  const regions = getRegions();

  // Add regions themselves
  for (const region of regions) {
    index.push({
      nameLower: region.name.toLowerCase(),
      result: {
        type: "region",
        name: region.name,
        slug: region.slug,
        region: { name: region.name, slug: region.slug },
        province: null,
      },
    });
  }

  // Add all locations
  for (const region of regions) {
    const data = getRegionData(region.slug);
    if (!data) continue;

    const locations = flattenLocations(data);
    for (const loc of locations) {
      index.push({
        nameLower: loc.name.toLowerCase(),
        result: {
          type: loc.type,
          name: loc.name,
          slug: loc.slug,
          region: { name: region.name, slug: region.slug },
          province: loc.province,
          zip_code: loc.zip_code,
        },
      });
    }
  }

  return index;
}

/**
 * Return the singleton search index (lazy-initialised on first call).
 */
export function getSearchIndex(): SearchIndexEntry[] {
  if (!_searchIndex) {
    _searchIndex = buildSearchIndex();
  }
  return _searchIndex;
}

/**
 * Search across regions and locations.
 *
 * @param query  Raw search string (will be lowercased internally)
 * @returns      Array of matching SearchResult objects
 */
export function search(query: string): SearchResult[] {
  const q = query.toLowerCase();
  const index = getSearchIndex();
  const results: SearchResult[] = [];

  for (const entry of index) {
    if (entry.nameLower.includes(q)) {
      results.push(entry.result);
    }
  }

  return results;
}

// ---------------------------------------------------------------------------
// Barangay lookup
// ---------------------------------------------------------------------------

/** Return the barangays for a specific location within a region. */
export function getBarangays(
  regionSlug: string,
  locationSlug: string,
): Barangay[] | null {
  const barangayFile = BARANGAY_DATA_MAP[regionSlug];
  if (!barangayFile) return null;

  const names = barangayFile.locations[locationSlug];
  if (!names) return null;

  return names.map((name) => ({ name, slug: toSlug(name) }));
}
